title: G Works @ GitHub!
date: 2018-06-29
author: grust101
email: grust101@github.com
description: > # this means to ignore newlines until "baseurl:"
  Here is my blog where I will share my experiences as a Hubber! 
# social links
twitter_username: georgiarust3
github_username:  grust101

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
